### ISSUE TITLE
Please add themeing options!

### ISSUE THREAD

**Issue by LoneWolf4713** [bootloopmaster636/kitshell#2]
Hi ! I loved kitshell and want to daily drive it, it's very promising and work till now is amazing too! loved the design.
so is there any way I can change the width to match my desktop and / or add some padding ? also, the apps menu shows a lot of apps which i don't have installed !
![image](https://github.com/user-attachments/assets/37be0aff-1621-4104-8ada-73872d83d810)
Amazing work dude! Just add some theming and matching colors based on wallpapers and it'll be ready to daily drive!

**Comment by bootloopmaster636** [comment]
Wow! Didn't think someone would discover this app, thank you very much 😄... I really appreciate it..

To change the width (and height (but it's still experimental)) you can do so by right clicking anywhere on the empty space to open the context menu, then you can open Kitshell settings... You can find many options, and customizations too :)...

Please be extra cautious when changing height and width, because I haven't put safeguard in place, and can be set to be over than your display's height/width...

Regarding the appmenu, can you give the example of the app which you don't have installed? I might be able to help...

**Comment by bootloopmaster636** [comment]
By the way, i do have a plan to rewrite this from scratch, maybe in a few months, because I'm still busy with my internship... 

I have plan to bring many feature, such as separate appmenu, calendars, notifications, etc.... but I'm still thinking about how to do this, because I have limited experience in wlroots, the library that I used is only able to display 1 things at a time...

**Comment by LoneWolf4713** [comment]
That settings did it ! It's fits perfectly, and among the apps, I have never in my life played Team Fortress 2 yet it shows up in my Apps list 😅, idk how. I did install steam in the past so it might be some error/artifact left by it, I don't know. btw congratulations on your internship, may you do well ! fellow CS Undergrad here too... 
and will be waiting for you to rewrite this, very promising project, who knows I may learn a little flutter till then and might be able to help...
kudos to you!

**Comment by bootloopmaster636** [comment]
Hmmm.... Looks like you might have Team Fortress 2 desktop file laying around after removing it 😅... Try using a desktop file editor (like alacarte) and you might find where it is...

Thank you very much for your support and good luck on your college too 😄

I will release 0.4.0 soon, will have some bugfixes and improvements

By the way, I'm sorry if my English is a bit weird, I'm not a native speaker...

Kudos to you :)
