### ISSUE TITLE
how can i contact you

### ISSUE THREAD

**Issue by Hanibachi** [bootloopmaster636/kitshell#3]
i ll apologize first for doing this here, but i couldn't find another way to contact u, i m a sway user and new flutter dev , been trying to write something up to configure my setup but i couldnt get wayland_layer_shell to work, can i trouble u for some advice?

**Comment by bootloopmaster636** [comment]
Hello, firstly, thanks for opening up new issue :) ... I haven't tried this on SwayWM, will try this in Sway tonight to see where the problem...

If you wanna have a chat, feel free to do so in my [Discord server](https://discord.com/channels/1092660851816812544/1321974553877942303)

**Comment by Hanibachi** [comment]
The link does point anywhere, the srme with the link on your profile btw
![Screenshot_20241227_015838_Iceraven](https://github.com/user-attachments/assets/63dcd05f-4f5f-4865-b51b-413f1f0902fe)

**Comment by bootloopmaster636** [comment]
Ah, my bad... can you please try [this link](https://discord.gg/tk39CTJd) ? sorry, i'm still a newbie at setting up Discord 😅

**Comment by bootloopmaster636** [comment]
Ah sorry, my bad... can you please try [this link](https://discord.gg/D9j7vJHKqZ) ? sorry, i'm still a newbie at setting up Discord 😅

**Comment by bootloopmaster636** [comment]
Hey @Hanibachi, I think i got the idea why this issue takes in the first place, what editor are you using?

When i am using VScode on X11 mode it also runs the shell in XWayland, so that might be the issue.

Try using VSCode with wayland option set [using the instructions at the ArchWiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Running_natively_under_Wayland)
